name: Release Binaries

on:
  push:
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+'

jobs:
  build:
    name: Build Cross-Platform Binaries
    runs-on: alpine/git

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - run: |
          go mod tidy
          go mod download

      - run: |
          mkdir -p bin

          GOOS=linux GOARCH=amd64 go build -o bin/pullio-linux-amd64 cmd/pullio/main.go

          GOOS=windows GOARCH=amd64 go build -o bin/pullio-windows-amd64.exe cmd/pullio/main.go

          GOOS=darwin GOARCH=amd64 go build -o bin/pullio-darwin-amd64 cmd/pullio/main.go

          GOOS=darwin GOARCH=arm64 go build -o bin/pullio-darwin-arm64 cmd/pullio/main.go

      - uses: actions/upload-artifact@v4
        with:
          name: pullio-binaries
          path: bin/

  release:
    name: Create GitHub Release
    runs-on: alpine/git
    needs: build

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: pullio-binaries

      - id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: pullio-*-*
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

