name: Release Binaries

on:
  push:
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+'

jobs:
  build:
    name: Build Cross-Platform Binaries
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
            ext: ""
            archive: tar.gz
          - goos: linux
            goarch: arm64
            ext: ""
            archive: tar.gz
          - goos: linux
            goarch: arm
            ext: ""
            archive: tar.gz
          - goos: linux
            goarch: 386
            ext: ""
            archive: tar.gz
          - goos: windows
            goarch: amd64
            ext: ".exe"
            archive: zip
          - goos: darwin
            goarch: amd64
            ext: ""
            archive: tar.gz
          - goos: darwin
            goarch: arm64
            ext: ""
            archive: tar.gz

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - run: |
          go mod tidy
          go mod download

      - name: Build and compress binary
        run: |
          mkdir -p bin
          BINARY_NAME=pullio-${{ github.ref_name }}-${{ matrix.goos }}-${{ matrix.goarch }}
          OUTPUT_NAME=$BINARY_NAME${{ matrix.ext }}

          # Build binary
          env GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} \
          go build -o $OUTPUT_NAME cmd/pullio/main.go

          # Package
          if [[ "${{ matrix.archive }}" == "zip" ]]; then
            zip -j bin/$BINARY_NAME.zip $OUTPUT_NAME
          else
            tar -czf bin/$BINARY_NAME.tar.gz $OUTPUT_NAME
          fi

      - uses: actions/upload-artifact@v4
        with:
          name: pullio-binaries-${{ github.ref_name }}-${{ matrix.goos }}-${{ matrix.goarch }}
          path: bin/

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write

    steps:
      - uses: actions/download-artifact@v4
        with:
          path: all-binaries

      - id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: all-binaries/**/pullio-*.{zip,tar.gz}
          prerelease:

